/**
 * Auto-discovers React Server Components and builds the RSC bundle.
 *
 * Usage:
 *   bun <this-script> [source-dir] [out-dir]
 *
 * Defaults:
 *   source-dir: resources/js/rsc
 *   out-dir:    bootstrap/rsc
 */

import { join, basename } from "node:path";
import { mkdirSync, writeFileSync } from "node:fs";

const sourceDir = process.argv[2] ?? join(process.cwd(), "resources/js/rsc");
const outDir = process.argv[3] ?? join(process.cwd(), "bootstrap/rsc");

const glob = new Bun.Glob("**/*.{tsx,ts,jsx,js}");
const components: { name: string; importAlias: string; relativePath: string }[] = [];
let aliasIndex = 0;

for await (const path of glob.scan(sourceDir)) {
  if (
    path.startsWith("entry.") ||
    path.includes(".test.") ||
    path.includes(".spec.") ||
    path.startsWith("_")
  ) {
    continue;
  }

  const name = basename(path).replace(/\.(tsx|ts|jsx|js)$/, "");
  components.push({ name, importAlias: `_C${aliasIndex++}`, relativePath: `./${path}` });
}

if (components.length === 0) {
  console.error(`No RSC components found in: ${sourceDir}`);
  console.error("Create component files (e.g. Dashboard.tsx or user-profile.tsx)");
  process.exit(1);
}

console.log(`Found ${components.length} component(s):`);
components.forEach((c) => console.log(`  ${c.name} ← ${c.relativePath}`));

const imports = components
  .map((c) => `import ${c.importAlias} from "${c.relativePath}";`)
  .join("\n");

const componentMap = components
  .map((c) => `  "${c.name}": ${c.importAlias},`)
  .join("\n");

const entrySource = `// Auto-generated by lara-bun build-rsc — do not edit
import { renderToReadableStream } from "react-server-dom-webpack/server.edge";
import { createElement } from "react";
${imports}

const components: Record<string, React.ComponentType<any>> = {
${componentMap}
};

export async function renderRsc(
  component: string,
  props: Record<string, unknown>
): Promise<string> {
  const Component = components[component];

  if (!Component) {
    throw new Error(
      \`Unknown RSC component: "\${component}". Available: \${Object.keys(components).join(", ")}\`
    );
  }

  const element = createElement(Component, props);
  const stream = renderToReadableStream(element, null);

  return await new Response(stream).text();
}
`;

const entryPath = join(sourceDir, "entry.rsc.tsx");
writeFileSync(entryPath, entrySource);
console.log(`Generated: ${entryPath}`);

mkdirSync(outDir, { recursive: true });

const result = await Bun.build({
  entrypoints: [entryPath],
  outdir: outDir,
  target: "bun",
  conditions: ["react-server"],
});

if (!result.success) {
  console.error("Build failed:");
  result.logs.forEach((log) => console.error(log));
  process.exit(1);
}

console.log(`Built: ${join(outDir, "entry.rsc.js")}`);
